### PR TITLE
Made PlcInvalidFieldException.java checked.

### PR DESCRIPTION
**Pull request by JulianFeinauer**
Made PlcInvalidFieldExeption checked, added UnchekedInvalidFieldException and changed everywhere.

### CODE REVIEW

**Comment by JulianFeinauer** [comment]
Hi @sruehl I think I cannot answer to your question directly, I think.
I get your point and in these points you point out it's true that I do not know what the appropriate handling is.
I opened a dicussion thread on the list to exchange the arguments and find a common understanding :)

**Comment by JulianFeinauer** [comment]
Hey @chrisdutz and @sruehl just wanted to bump that up. I think we should decide here on something and either merge or decline the PR. What do you hink about the checked exceptions for wrong user inputs?

**Comment by sruehl** [comment]
As I said: The annoyance to be forked to catch a exception would outweigh the benefit. In the usual api use this would a one-time-occur-exception so we would require the developer to pollute the code with catch(e) new RuntimeException(e) snippets. So I would suggest/vote to close this PR and maybe pickup the topic in later releases (if at all).

**Comment by JulianFeinauer** [comment]
Closing as suggested by sebastian.
But I definitly like to adress the topic nonetheless as we heavily depend on user input which can always be errorous.

**Pull request closed without merging**
