### PR TITLE
S7 fix of array and String acquirement

### PR DESCRIPTION
**Pull request by timbo2k**
S7: fix of array acquirement, fix of String aquirement, added additional scraper yml

### CODE REVIEW

**Comment by JulianFeinauer** [comment]
Looks good to me (also checked it against our S7).
@chrisdutz  do you want to look over it, otherwise I'll merge it.

**Comment by ottobackwards** [comment]
Are there no tests?

**Comment by chrisdutz** [comment]
Feel free to merge ...

**Comment by JulianFeinauer** [comment]
> Are there no tests?

Hey Otto, the only way to test this PLC Communication is through manual tests (this is why there is this yml file). So we did manual tests.

**Pull request merged**
