### PR TITLE
fix a few typos

### PR DESCRIPTION
**Pull request by bodewig**
Found a few typos while reading the DeltaV story.

### CODE REVIEW

**Comment by chrisdutz** [comment]
Well I guess I can simply merge this from the GitHub ui ... thanks for this :-)

**Comment by chrisdutz** [comment]
And it does seem as if this revealed syncing problems from GitHub back to GitBox ... will investigate this.

**Comment by bodewig** [comment]
As somebody toying with the idea of using gitbox for some other projects I'd be interested in hearing what went wrong :-)

**Comment by chrisdutz** [comment]
Ok ... so the commit was in GitHub (d2203536d91b05945c6bbe41d1110eeb20a6918c) but that wasn't synced back to GitBox ... I had to manually pull the GitHub repo and push that to GitBox as not even the self-service tool (https://gitbox.apache.org/setup/resync.cgi) was able to get them back in sync. Will ask Infra about this ...

**Pull request merged**
